---
title: "FTAP Homework 10"
author: "Zachary Fogelson"
date: "July 25, 2015"
output: html_document
---

```{r, include = F}
require(timeSeries)
require(tseries)
require(stats)
require(forecast)
library(xts)
library(gdata)
library(plyr)
library(knitr)
library(ggplot2)
library(forecast)
require(plotrix)
library(fGarch)
require(splines)
```
### Problem 1

***Read and Format Problem 1:***

```{r}
orderByDate <- function (x){
  x$DateTime <- as.Date(x$Date, "%Y-%m-%d")
  x <- x[order(x$DateTime, decreasing=F),]
  x <- x[complete.cases(x),]
  x
}

logRateReturn <- function(x){
  x$logReturn <- c(NA, diff(log(x$Adj.Close)))
  x
}

riskFreeReturn <- function(x){
  x$excessReturn <- x$logReturn - tbill$WeeklyReturn
  x
}

tbill <- read.xls("tbillWeek.xls", skip = 8)
tbill <- rename(x = tbill, c("observation_date" = "Date", "WTB3MS"="Return"))
tbill$RawReturn <- tbill$Return / 100
tbill$WeeklyReturn <- tbill$RawReturn / 52
spy <- read.csv("spy.csv")
spy <- orderByDate(spy)
spy <- logRateReturn(spy)[-1,]
spy <- riskFreeReturn(spy)

bestBuy <- read.csv("bby.csv")
bestBuy <- orderByDate(bestBuy)
bestBuy <- logRateReturn(bestBuy)[-1,]
bestBuy <- riskFreeReturn(bestBuy)

homeDepot <- read.csv("hd.csv")
homeDepot <- orderByDate(homeDepot)
homeDepot <- logRateReturn(homeDepot)[-1,]
homeDepot <- riskFreeReturn(homeDepot)
```


***a***
```{r}
lm.bestBuy <-lm(bestBuy$excessReturn~spy$excessReturn)
v.bestBuy <- var(lm.bestBuy$residuals)
beta.bestBuy <- as.numeric(lm.bestBuy$coefficients["spy$excessReturn"])

lm.homeDepot <-lm(homeDepot$excessReturn~spy$excessReturn)
v.homeDepot <- var(lm.homeDepot$residuals)
beta.homeDepot <- as.numeric(lm.homeDepot$coefficients["spy$excessReturn"])
```

***b***
```{r}
garch <- garchFit(~garch(2,2),data=spy$excessReturn, trace = F)
vol <- volatility(garch)
plot(vol, type="l")
```


***c***

Conditional Correlation
```{r}
cov <- beta.bestBuy*beta.homeDepot*vol^2
denom.bestBuy <- beta.bestBuy^2*vol^2+mean(residuals(lm.bestBuy)^2)
denom.homeDepot <- beta.homeDepot^2*vol^2+mean(residuals(lm.homeDepot)^2)

corr=cov/sqrt(denom.bestBuy*denom.homeDepot)
```

***d***
```{r}
plot(bestBuy$DateTime,corr,type="l", col="blue")
```

***e***
```{r}
forecast <- predict(garch,n.ahead=1)
oneDayVar <- .3^2*(beta.bestBuy^2*forecast$standardDeviation^2 +  var(lm.bestBuy$residuals)) + .7^2*(beta.homeDepot^2*forecast$standardDeviation^2 + var(lm.homeDepot$residuals)) + 2 * cov[length(bestBuy$excessReturn)]*.3*.7
oneDayVar
```

***f***
```{r}
valrisk_norm<-qnorm(.010,0,1)*sqrt((oneDayVar/length(bestBuy$excessReturn)))
valrisk_norm*1000000
```


### Problem 2

***Read and Format Problem 2:***

```{r}
riskFreeDaily <- function(x){
  x$excessReturn <- x$logReturn - tbillDaily$RawReturn
  x
}

spyDaily <- read.csv("spyDaily.csv")
spyDaily <- orderByDate(spyDaily)
spyDaily <- logRateReturn(spyDaily)[-1,]

tbillDaily <- read.xls("tbill.xls", skip = 8)
tbillDaily <- rename(x = tbillDaily, c("observation_date" = "Date", "DTB3"="Return"))
tbillDaily$DateTime <- as.Date(tbillDaily$Date, "%Y-%m-%d")
tbillDaily <- tbillDaily[tbillDaily$DateTime > as.Date("1999-12-31", "%Y-%m-%d"), ]
tbillDaily$RawReturn <- tbillDaily$Return / 100

att <- read.csv("tDaily.csv")
att <- orderByDate(att)
att <- logRateReturn(att)[-1,]

msft <- read.csv("msftDaily.csv")
msft <- orderByDate(msft)
msft <- logRateReturn(msft)[-1,]

sam <- read.csv("samDaily.csv")
sam <- orderByDate(sam)
sam <- logRateReturn(sam)[-1,]


ba <- read.csv("baDaily.csv")
ba <- orderByDate(ba)
ba <- logRateReturn(ba)[-1,]

gs <- read.csv("gsDaily.csv")
gs <- orderByDate(gs)
gs <- logRateReturn(gs)[-1,]

```

***a***

```{r}
oneFactor <- function(x, y){
#   lm.x <- lm(x$logReturn~spyDaily$logReturn)
#   lm.x$coefficients <- rename(lm.x$coefficients, c("spyDaily$logReturn"=y))
#   lm.x
  lm(x$logReturn~spyDaily$logReturn)
}

lm.att <- oneFactor(att, "attBeta")
lm.msft <- oneFactor(msft, "msftBeta")
lm.sam <- oneFactor(sam, "samBeta")
lm.ba <- oneFactor(ba, "boeingBeta")
lm.gs <- oneFactor(gs, "gsBeta")
```

***b***
```{r}
all.betas <- c(lm.gs$coefficients[2], lm.ba$coefficients[2], 
              lm.sam$coefficients[2], lm.msft$coefficients[2],
              lm.att$coefficients[2])

all.residVar <- sapply(list(gsResid = lm.gs$residuals, baResid = lm.ba$residuals, 
              samResid = lm.sam$residuals, msftResid = lm.msft$residuals,
              attResid = lm.att$residuals), var)

kable(head(outer(all.betas, all.betas) * var(spyDaily$logReturn) + diag(5) * all.residVar))
```

### Problem 3

***a***

(Assuming that the final marginal probability is irrelavant for cleanliness)

$$L = f(x_N | F_{N-1, \theta}) *...* f(x_2 | F_{1,  \theta})$$
$$\mathcal{L} = log(f(x_N | F_{N-1, \theta})) +...+ log(f(x_2 | F_{1,  \theta}))$$
$$\mathcal{L} = \Sigma_2^N log(f(x_i | F_{i-1, \theta}))$$
$$\mathcal{L} = \Sigma_2^N log(\frac{1}{\omega + \alpha * x_{i-1}} e^{\frac{-x_i}{\omega + \alpha * x_{i-1}}})$$

$$\mathcal{L} = \Sigma_2^N -log(\omega + \alpha * x_{i-1}) + \frac{-x_i}{\omega + \alpha * x_{i-1}}$$

***b***

Assume $x_i$ in the conditional probability function should be an $x_{i-1}$
Let $U = \omega + \alpha * x_{i-1}$

$$\frac{d\mathcal{L}}{d\alpha} = \Sigma_2^N(-\frac{1}{U}*\frac{dU}{d\alpha} + x_{i-1}\frac{1}{U^2}*\frac{dU}{d\alpha})$$

$$\frac{dU}{d\alpha} = x_{i-1}$$

$$\frac{d\mathcal{L}}{d\alpha} = \Sigma_2^N(-\frac{x_{i-1}}{\omega + \alpha * x_{i-1}} + \frac{x_{i-1}^2}{(\omega + \alpha * x_{i-1})^2})$$

\hline

$$\frac{d\mathcal{L}}{d\omega} = \Sigma_2^N(-\frac{1}{U}*\frac{dU}{d\omega} + x_{i-1}\frac{1}{U^2}*\frac{dU}{d\omega})$$

$$\frac{dU}{d\omega} = 1$$

$$\frac{d\mathcal{L}}{d\omega} = \Sigma_2^N(-\frac{1}{\omega + \alpha * x_{i-1}} + \frac{x_{i-1}}{(\omega + \alpha * x_{i-1})^2})$$


***c***


$$\frac{d^2\mathcal{L}}{d^2\alpha} = $$\frac{d\mathcal{L}}{d\alpha} = \Sigma_2^N(-\frac{x_{i-1}}{\omega + \alpha * x_{i-1}} + \frac{x_{i-1}^2}{(\omega + \alpha * x_{i-1})^2})$$



